---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/jamescherti/pre-commit-elisp
    rev: v1.0.8
    hooks:
      - id: elisp-check-parens
      - id: elisp-check-byte-compile
        exclude: '(\.dir-locals\.el|test-easysession\.el)$'
      # - id: elisp-check-native-compile
      #   exclude: '\.dir-locals\.el$'
